#!/usr/bin/env bash
# if else

i=1

while [ $i < 10 ]; do
	echo "Best School"
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		continue
	
	(( i++ ))
	fi
done
